In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("OnePieceArcs.csv")
df.head()

,Arc,Start onChapter,TotalChapters,TotalPages,Manga%,Start onEpisode,TotalEpisodes,TotalMinutes(avg 24),Anime%
0,Romance Dawn Arc,1,7,178,0.9%,1,3,72,0.3%
1,Orange Town Arc,8,14,273,1.4%,4,5,120,0.5%
2,Syrup Village Arc,22,20,396,2.0%,9,10,240,1.0%
3,Baratie Arc,42,27,514,2.6%,19,12,288,1.2%
4,Arlong Park Arc,69,27,514,2.6%,31,15,360,1.5%

In [4]:
df.head()

,Arc,Start onChapter,TotalChapters,TotalPages,Manga%,Start onEpisode,TotalEpisodes,TotalMinutes(avg 24),Anime%
0,Romance Dawn Arc,1,7,178,0.9%,1,3,72,0.3%
1,Orange Town Arc,8,14,273,1.4%,4,5,120,0.5%
2,Syrup Village Arc,22,20,396,2.0%,9,10,240,1.0%
3,Baratie Arc,42,27,514,2.6%,19,12,288,1.2%
4,Arlong Park Arc,69,27,514,2.6%,31,15,360,1.5%

In [5]:
df.set_index("Arc", inplace=True)
df.head()

,Start onChapter,TotalChapters,TotalPages,Manga%,Start onEpisode,TotalEpisodes,TotalMinutes(avg 24),Anime%
Arc,,,,,,,,
Romance Dawn Arc,1,7,178,0.9%,1,3,72,0.3%
Orange Town Arc,8,14,273,1.4%,4,5,120,0.5%
Syrup Village Arc,22,20,396,2.0%,9,10,240,1.0%
Baratie Arc,42,27,514,2.6%,19,12,288,1.2%
Arlong Park Arc,69,27,514,2.6%,31,15,360,1.5%